// THIS CODE WAS GENERATED BY SH4GENERATOR v0.1.0 BY FRANCISZEK ŁOPUSZAŃSKI
#![allow(unused)]
use std::fmt;

#[derive(Debug, Clone)]
pub struct OpCode {
    pub id: usize,
    pub display: String,
    pub mask: u16,
    pub code: u16,
    pub args: OpCodeArgs,
}

impl fmt::Display for OpCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut display = self.display.clone();

        display = display.replace(",", ", ");
        display = display.replace("Rn", &format!("R{}", self.args.n));
        display = display.replace("Rm", &format!("R{}", self.args.m));
        display = display.replace("disp", &format!("R{}", self.args.d));
        display = display.replace("#imm", &format!("0x{:04X}", self.args.i));
        display = display.trim().to_string();

        write!(f, "{}", display)
    }
}

#[derive(Debug, Default, Clone, Copy)]
pub struct OpCodeArgs {
    pub n: u16,
    pub m: u16,
    pub i: u16,
    pub d: u16,
}

impl OpCode {
    pub fn decode_instruction(inp: u16) -> Option<OpCode> {
        for opcode in OPCODES_TABLE.iter() {
            if (inp & opcode.mask) != opcode.code {
                continue;
            }

            let mut res = opcode.clone();

            fn set_arg(inp: u16, mask: u16) -> u16 {
                if mask == 0 {
                    return 0;
                }

                (inp & mask) >> mask.trailing_zeros()
            }

            res.args.n = set_arg(inp, opcode.args.n);
            res.args.m = set_arg(inp, opcode.args.m);
            res.args.d = set_arg(inp, opcode.args.d);
            res.args.i = set_arg(inp, opcode.args.i);

            return Some(res);
        }

        None
    }
}

lazy_static! {
    pub static ref OPCODES_TABLE: [OpCode; 246] = [
        OpCode {
            id: 0,
            display: "mov Rm,Rn".to_string(),
            mask: 61455,
            code: 24579,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 1,
            display: "mov #imm,Rn".to_string(),
            mask: 61440,
            code: 57344,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 4,
            display: "mova @(disp,PC),R0".to_string(),
            mask: 65280,
            code: 50944,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 5,
            display: "mov.w @(disp,PC),Rn".to_string(),
            mask: 61440,
            code: 36864,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 6,
            display: "mov.l @(disp,PC),Rn".to_string(),
            mask: 61440,
            code: 53248,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 7,
            display: "mov.b @Rm,Rn".to_string(),
            mask: 61455,
            code: 24576,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 8,
            display: "mov.w @Rm,Rn".to_string(),
            mask: 61455,
            code: 24577,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 9,
            display: "mov.l @Rm,Rn".to_string(),
            mask: 61455,
            code: 24578,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 10,
            display: "mov.b Rm,@Rn".to_string(),
            mask: 61455,
            code: 8192,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 11,
            display: "mov.w Rm,@Rn".to_string(),
            mask: 61455,
            code: 8193,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 12,
            display: "mov.l Rm,@Rn".to_string(),
            mask: 61455,
            code: 8194,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 13,
            display: "mov.b @Rm+,Rn".to_string(),
            mask: 61455,
            code: 24580,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 14,
            display: "mov.w @Rm+,Rn".to_string(),
            mask: 61455,
            code: 24581,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 15,
            display: "mov.l @Rm+,Rn".to_string(),
            mask: 61455,
            code: 24582,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 16,
            display: "mov.b Rm,@-Rn".to_string(),
            mask: 61455,
            code: 8196,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 17,
            display: "mov.w Rm,@-Rn".to_string(),
            mask: 61455,
            code: 8197,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 18,
            display: "mov.l Rm,@-Rn".to_string(),
            mask: 61455,
            code: 8198,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 25,
            display: "mov.b @(disp,Rm),R0".to_string(),
            mask: 65280,
            code: 33792,
            args: OpCodeArgs {
                n: 0,
                m: 240,
                d: 15,
                i: 0
            }
        } ,

        OpCode {
            id: 28,
            display: "mov.w @(disp,Rm),R0".to_string(),
            mask: 65280,
            code: 34048,
            args: OpCodeArgs {
                n: 0,
                m: 240,
                d: 15,
                i: 0
            }
        } ,

        OpCode {
            id: 31,
            display: "mov.l @(disp,Rm),Rn".to_string(),
            mask: 61440,
            code: 20480,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 15,
                i: 0
            }
        } ,

        OpCode {
            id: 33,
            display: "mov.b R0,@(disp,Rn)".to_string(),
            mask: 65280,
            code: 32768,
            args: OpCodeArgs {
                n: 240,
                m: 0,
                d: 15,
                i: 0
            }
        } ,

        OpCode {
            id: 35,
            display: "mov.w R0,@(disp,Rn)".to_string(),
            mask: 65280,
            code: 33024,
            args: OpCodeArgs {
                n: 240,
                m: 0,
                d: 15,
                i: 0
            }
        } ,

        OpCode {
            id: 37,
            display: "mov.l Rm,@(disp,Rn)".to_string(),
            mask: 61440,
            code: 4096,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 15,
                i: 0
            }
        } ,

        OpCode {
            id: 39,
            display: "mov.b @(R0,Rm),Rn".to_string(),
            mask: 61455,
            code: 12,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 40,
            display: "mov.w @(R0,Rm),Rn".to_string(),
            mask: 61455,
            code: 13,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 41,
            display: "mov.l @(R0,Rm),Rn".to_string(),
            mask: 61455,
            code: 14,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 42,
            display: "mov.b Rm,@(R0,Rn)".to_string(),
            mask: 61455,
            code: 4,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 43,
            display: "mov.w Rm,@(R0,Rn)".to_string(),
            mask: 61455,
            code: 5,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 44,
            display: "mov.l Rm,@(R0,Rn)".to_string(),
            mask: 61455,
            code: 6,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 45,
            display: "mov.b @(disp,GBR),R0".to_string(),
            mask: 65280,
            code: 50176,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 46,
            display: "mov.w @(disp,GBR),R0".to_string(),
            mask: 65280,
            code: 50432,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 47,
            display: "mov.l @(disp,GBR),R0".to_string(),
            mask: 65280,
            code: 50688,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 48,
            display: "mov.b R0,@(disp,GBR)".to_string(),
            mask: 65280,
            code: 49152,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 49,
            display: "mov.w R0,@(disp,GBR)".to_string(),
            mask: 65280,
            code: 49408,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 50,
            display: "mov.l R0,@(disp,GBR)".to_string(),
            mask: 65280,
            code: 49664,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 51,
            display: "movco.l R0,@Rn".to_string(),
            mask: 61695,
            code: 115,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 52,
            display: "movli.l @Rm,R0".to_string(),
            mask: 61695,
            code: 99,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 53,
            display: "movua.l @Rm,R0".to_string(),
            mask: 61695,
            code: 16553,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 54,
            display: "movua.l @Rm+,R0".to_string(),
            mask: 61695,
            code: 16617,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 60,
            display: "movt Rn".to_string(),
            mask: 61695,
            code: 41,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 62,
            display: "swap.b Rm,Rn".to_string(),
            mask: 61455,
            code: 24584,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 63,
            display: "swap.w Rm,Rn".to_string(),
            mask: 61455,
            code: 24585,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 64,
            display: "xtrct Rm,Rn".to_string(),
            mask: 61455,
            code: 8205,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 79,
            display: "add Rm,Rn".to_string(),
            mask: 61455,
            code: 12300,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 80,
            display: "add #imm,Rn".to_string(),
            mask: 61440,
            code: 28672,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 81,
            display: "addc Rm,Rn".to_string(),
            mask: 61455,
            code: 12302,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 82,
            display: "addv Rm,Rn".to_string(),
            mask: 61455,
            code: 12303,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 83,
            display: "cmp/eq #imm,R0".to_string(),
            mask: 65280,
            code: 34816,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 84,
            display: "cmp/eq Rm,Rn".to_string(),
            mask: 61455,
            code: 12288,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 85,
            display: "cmp/hs Rm,Rn".to_string(),
            mask: 61455,
            code: 12290,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 86,
            display: "cmp/ge Rm,Rn".to_string(),
            mask: 61455,
            code: 12291,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 87,
            display: "cmp/hi Rm,Rn".to_string(),
            mask: 61455,
            code: 12294,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 88,
            display: "cmp/gt Rm,Rn".to_string(),
            mask: 61455,
            code: 12295,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 89,
            display: "cmp/pl Rn".to_string(),
            mask: 61695,
            code: 16405,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 90,
            display: "cmp/pz Rn".to_string(),
            mask: 61695,
            code: 16401,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 91,
            display: "cmp/str Rm,Rn".to_string(),
            mask: 61455,
            code: 8204,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 96,
            display: "div0s Rm,Rn".to_string(),
            mask: 61455,
            code: 8199,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 97,
            display: "div0u".to_string(),
            mask: 65535,
            code: 25,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 98,
            display: "div1 Rm,Rn".to_string(),
            mask: 61455,
            code: 12292,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 101,
            display: "dmuls.l Rm,Rn".to_string(),
            mask: 61455,
            code: 12301,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 102,
            display: "dmulu.l Rm,Rn".to_string(),
            mask: 61455,
            code: 12293,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 103,
            display: "dt Rn".to_string(),
            mask: 61695,
            code: 16400,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 104,
            display: "exts.b Rm,Rn".to_string(),
            mask: 61455,
            code: 24590,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 105,
            display: "exts.w Rm,Rn".to_string(),
            mask: 61455,
            code: 24591,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 106,
            display: "extu.b Rm,Rn".to_string(),
            mask: 61455,
            code: 24588,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 107,
            display: "extu.w Rm,Rn".to_string(),
            mask: 61455,
            code: 24589,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 108,
            display: "mac.l @Rm+,@Rn+".to_string(),
            mask: 61455,
            code: 15,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 109,
            display: "mac.w @Rm+,@Rn+".to_string(),
            mask: 61455,
            code: 16399,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 110,
            display: "mul.l Rm,Rn".to_string(),
            mask: 61455,
            code: 7,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 112,
            display: "muls.w Rm,Rn".to_string(),
            mask: 61455,
            code: 8207,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 113,
            display: "mulu.w Rm,Rn".to_string(),
            mask: 61455,
            code: 8206,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 114,
            display: "neg Rm,Rn".to_string(),
            mask: 61455,
            code: 24587,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 115,
            display: "negc Rm,Rn".to_string(),
            mask: 61455,
            code: 24586,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 116,
            display: "sub Rm,Rn".to_string(),
            mask: 61455,
            code: 12296,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 117,
            display: "subc Rm,Rn".to_string(),
            mask: 61455,
            code: 12298,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 118,
            display: "subv Rm,Rn".to_string(),
            mask: 61455,
            code: 12299,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 119,
            display: "and Rm,Rn".to_string(),
            mask: 61455,
            code: 8201,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 120,
            display: "and #imm,R0".to_string(),
            mask: 65280,
            code: 51456,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 121,
            display: "and.b #imm,@(R0,GBR)".to_string(),
            mask: 65280,
            code: 52480,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 122,
            display: "not Rm,Rn".to_string(),
            mask: 61455,
            code: 24583,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 123,
            display: "or Rm,Rn".to_string(),
            mask: 61455,
            code: 8203,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 124,
            display: "or #imm,R0".to_string(),
            mask: 65280,
            code: 51968,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 125,
            display: "or.b #imm,@(R0,GBR)".to_string(),
            mask: 65280,
            code: 52992,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 126,
            display: "tas.b @Rn".to_string(),
            mask: 61695,
            code: 16411,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 127,
            display: "tst Rm,Rn".to_string(),
            mask: 61455,
            code: 8200,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 128,
            display: "tst #imm,R0".to_string(),
            mask: 65280,
            code: 51200,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 129,
            display: "tst.b #imm,@(R0,GBR)".to_string(),
            mask: 65280,
            code: 52224,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 130,
            display: "xor Rm,Rn".to_string(),
            mask: 61455,
            code: 8202,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 131,
            display: "xor #imm,R0".to_string(),
            mask: 65280,
            code: 51712,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 132,
            display: "xor.b #imm,@(R0,GBR)".to_string(),
            mask: 65280,
            code: 52736,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 133,
            display: "rotcl Rn".to_string(),
            mask: 61695,
            code: 16420,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 134,
            display: "rotcr Rn".to_string(),
            mask: 61695,
            code: 16421,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 135,
            display: "rotl Rn".to_string(),
            mask: 61695,
            code: 16388,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 136,
            display: "rotr Rn".to_string(),
            mask: 61695,
            code: 16389,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 137,
            display: "shad Rm,Rn".to_string(),
            mask: 61455,
            code: 16396,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 138,
            display: "shal Rn".to_string(),
            mask: 61695,
            code: 16416,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 139,
            display: "shar Rn".to_string(),
            mask: 61695,
            code: 16417,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 140,
            display: "shld Rm,Rn".to_string(),
            mask: 61455,
            code: 16397,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 141,
            display: "shll Rn".to_string(),
            mask: 61695,
            code: 16384,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 142,
            display: "shll2 Rn".to_string(),
            mask: 61695,
            code: 16392,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 143,
            display: "shll8 Rn".to_string(),
            mask: 61695,
            code: 16408,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 144,
            display: "shll16 Rn".to_string(),
            mask: 61695,
            code: 16424,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 145,
            display: "shlr Rn".to_string(),
            mask: 61695,
            code: 16385,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 146,
            display: "shlr2 Rn".to_string(),
            mask: 61695,
            code: 16393,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 147,
            display: "shlr8 Rn".to_string(),
            mask: 61695,
            code: 16409,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 148,
            display: "shlr16 Rn".to_string(),
            mask: 61695,
            code: 16425,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 149,
            display: "bf label".to_string(),
            mask: 65280,
            code: 35584,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 150,
            display: "bf/s label".to_string(),
            mask: 65280,
            code: 36608,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 151,
            display: "bt label".to_string(),
            mask: 65280,
            code: 35072,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 152,
            display: "bt/s label".to_string(),
            mask: 65280,
            code: 36096,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 255,
                i: 0
            }
        } ,

        OpCode {
            id: 153,
            display: "bra label".to_string(),
            mask: 61440,
            code: 40960,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 4095,
                i: 0
            }
        } ,

        OpCode {
            id: 154,
            display: "braf Rm".to_string(),
            mask: 61695,
            code: 35,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 155,
            display: "bsr label".to_string(),
            mask: 61440,
            code: 45056,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 4095,
                i: 0
            }
        } ,

        OpCode {
            id: 156,
            display: "bsrf Rm".to_string(),
            mask: 61695,
            code: 3,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 157,
            display: "jmp @Rm".to_string(),
            mask: 61695,
            code: 16427,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 158,
            display: "jsr @Rm".to_string(),
            mask: 61695,
            code: 16395,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 161,
            display: "rts".to_string(),
            mask: 65535,
            code: 11,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 164,
            display: "clrmac".to_string(),
            mask: 65535,
            code: 40,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 165,
            display: "clrs".to_string(),
            mask: 65535,
            code: 72,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 166,
            display: "clrt".to_string(),
            mask: 65535,
            code: 8,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 167,
            display: "icbi @Rn".to_string(),
            mask: 61695,
            code: 227,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 169,
            display: "ldc Rm,SR".to_string(),
            mask: 61695,
            code: 16398,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 170,
            display: "ldc.l @Rm+,SR".to_string(),
            mask: 61695,
            code: 16391,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 172,
            display: "ldc Rm,GBR".to_string(),
            mask: 61695,
            code: 16414,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 173,
            display: "ldc.l @Rm+,GBR".to_string(),
            mask: 61695,
            code: 16407,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 174,
            display: "ldc Rm,VBR".to_string(),
            mask: 61695,
            code: 16430,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 175,
            display: "ldc.l @Rm+,VBR".to_string(),
            mask: 61695,
            code: 16423,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 182,
            display: "ldc Rm,SGR".to_string(),
            mask: 61695,
            code: 16442,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 183,
            display: "ldc.l @Rm+,SGR".to_string(),
            mask: 61695,
            code: 16438,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 184,
            display: "ldc Rm,SSR".to_string(),
            mask: 61695,
            code: 16446,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 185,
            display: "ldc.l @Rm+,SSR".to_string(),
            mask: 61695,
            code: 16439,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 186,
            display: "ldc Rm,SPC".to_string(),
            mask: 61695,
            code: 16462,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 187,
            display: "ldc.l @Rm+,SPC".to_string(),
            mask: 61695,
            code: 16455,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 188,
            display: "ldc Rm,DBR".to_string(),
            mask: 61695,
            code: 16634,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 189,
            display: "ldc.l @Rm+,DBR".to_string(),
            mask: 61695,
            code: 16630,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 190,
            display: "ldc Rm,Rn_BANK".to_string(),
            mask: 61583,
            code: 16526,
            args: OpCodeArgs {
                n: 112,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 191,
            display: "ldc.l @Rm+,Rn_BANK".to_string(),
            mask: 61583,
            code: 16519,
            args: OpCodeArgs {
                n: 112,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 194,
            display: "lds Rm,MACH".to_string(),
            mask: 61695,
            code: 16394,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 195,
            display: "lds.l @Rm+,MACH".to_string(),
            mask: 61695,
            code: 16390,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 196,
            display: "lds Rm,MACL".to_string(),
            mask: 61695,
            code: 16410,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 197,
            display: "lds.l @Rm+,MACL".to_string(),
            mask: 61695,
            code: 16406,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 198,
            display: "lds Rm,PR".to_string(),
            mask: 61695,
            code: 16426,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 199,
            display: "lds.l @Rm+,PR".to_string(),
            mask: 61695,
            code: 16422,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 212,
            display: "ldtlb".to_string(),
            mask: 65535,
            code: 56,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 213,
            display: "movca.l R0,@Rn".to_string(),
            mask: 61695,
            code: 195,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 214,
            display: "nop".to_string(),
            mask: 65535,
            code: 9,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 215,
            display: "ocbi @Rn".to_string(),
            mask: 61695,
            code: 147,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 216,
            display: "ocbp @Rn".to_string(),
            mask: 61695,
            code: 163,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 217,
            display: "ocbwb @Rn".to_string(),
            mask: 61695,
            code: 179,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 218,
            display: "pref @Rn".to_string(),
            mask: 61695,
            code: 131,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 219,
            display: "prefi @Rn".to_string(),
            mask: 61695,
            code: 211,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 221,
            display: "rte".to_string(),
            mask: 65535,
            code: 43,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 224,
            display: "sets".to_string(),
            mask: 65535,
            code: 88,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 225,
            display: "sett".to_string(),
            mask: 65535,
            code: 24,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 226,
            display: "sleep".to_string(),
            mask: 65535,
            code: 27,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 228,
            display: "stc SR,Rn".to_string(),
            mask: 61695,
            code: 2,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 229,
            display: "stc.l SR,@-Rn".to_string(),
            mask: 61695,
            code: 16387,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 231,
            display: "stc GBR,Rn".to_string(),
            mask: 61695,
            code: 18,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 232,
            display: "stc.l GBR,@-Rn".to_string(),
            mask: 61695,
            code: 16403,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 233,
            display: "stc VBR,Rn".to_string(),
            mask: 61695,
            code: 34,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 234,
            display: "stc.l VBR,@-Rn".to_string(),
            mask: 61695,
            code: 16419,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 241,
            display: "stc SGR,Rn".to_string(),
            mask: 61695,
            code: 58,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 242,
            display: "stc.l SGR,@-Rn".to_string(),
            mask: 61695,
            code: 16434,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 243,
            display: "stc SSR,Rn".to_string(),
            mask: 61695,
            code: 50,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 244,
            display: "stc.l SSR,@-Rn".to_string(),
            mask: 61695,
            code: 16435,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 245,
            display: "stc SPC,Rn".to_string(),
            mask: 61695,
            code: 66,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 246,
            display: "stc.l SPC,@-Rn".to_string(),
            mask: 61695,
            code: 16451,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 247,
            display: "stc DBR,Rn".to_string(),
            mask: 61695,
            code: 250,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 248,
            display: "stc.l DBR,@-Rn".to_string(),
            mask: 61695,
            code: 16626,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 249,
            display: "stc Rm_BANK,Rn".to_string(),
            mask: 61583,
            code: 130,
            args: OpCodeArgs {
                n: 3840,
                m: 112,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 250,
            display: "stc.l Rm_BANK,@-Rn".to_string(),
            mask: 61583,
            code: 16515,
            args: OpCodeArgs {
                n: 3840,
                m: 112,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 251,
            display: "sts MACH,Rn".to_string(),
            mask: 61695,
            code: 10,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 252,
            display: "sts.l MACH,@-Rn".to_string(),
            mask: 61695,
            code: 16386,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 253,
            display: "sts MACL,Rn".to_string(),
            mask: 61695,
            code: 26,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 254,
            display: "sts.l MACL,@-Rn".to_string(),
            mask: 61695,
            code: 16402,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 255,
            display: "sts PR,Rn".to_string(),
            mask: 61695,
            code: 42,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 256,
            display: "sts.l PR,@-Rn".to_string(),
            mask: 61695,
            code: 16418,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 269,
            display: "synco".to_string(),
            mask: 65535,
            code: 171,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 270,
            display: "trapa #imm".to_string(),
            mask: 65280,
            code: 49920,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 255
            }
        } ,

        OpCode {
            id: 271,
            display: "fmov FRm,FRn".to_string(),
            mask: 61455,
            code: 61452,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 272,
            display: "fmov.s @Rm,FRn".to_string(),
            mask: 61455,
            code: 61448,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 273,
            display: "fmov.s FRm,@Rn".to_string(),
            mask: 61455,
            code: 61450,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 274,
            display: "fmov.s @Rm+,FRn".to_string(),
            mask: 61455,
            code: 61449,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 275,
            display: "fmov.s FRm,@-Rn".to_string(),
            mask: 61455,
            code: 61451,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 276,
            display: "fmov.s @(R0,Rm),FRn".to_string(),
            mask: 61455,
            code: 61446,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 277,
            display: "fmov.s FRm,@(R0,Rn)".to_string(),
            mask: 61455,
            code: 61447,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 280,
            display: "fmov DRm,DRn".to_string(),
            mask: 61727,
            code: 61452,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 281,
            display: "fmov DRm,XDn".to_string(),
            mask: 61727,
            code: 61708,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 282,
            display: "fmov XDm,DRn".to_string(),
            mask: 61727,
            code: 61468,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 283,
            display: "fmov XDm,XDn".to_string(),
            mask: 61727,
            code: 61724,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 284,
            display: "fmov.d @Rm,DRn".to_string(),
            mask: 61711,
            code: 61448,
            args: OpCodeArgs {
                n: 3584,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 285,
            display: "fmov.d @Rm,XDn".to_string(),
            mask: 61711,
            code: 61704,
            args: OpCodeArgs {
                n: 3584,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 286,
            display: "fmov.d DRm,@Rn".to_string(),
            mask: 61471,
            code: 61450,
            args: OpCodeArgs {
                n: 3840,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 287,
            display: "fmov.d XDm,@Rn".to_string(),
            mask: 61471,
            code: 61466,
            args: OpCodeArgs {
                n: 3840,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 288,
            display: "fmov.d @Rm+,DRn".to_string(),
            mask: 61711,
            code: 61449,
            args: OpCodeArgs {
                n: 3584,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 289,
            display: "fmov.d @Rm+,XDn".to_string(),
            mask: 61711,
            code: 61705,
            args: OpCodeArgs {
                n: 3584,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 290,
            display: "fmov.d DRm,@-Rn".to_string(),
            mask: 61471,
            code: 61451,
            args: OpCodeArgs {
                n: 3840,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 291,
            display: "fmov.d XDm,@-Rn".to_string(),
            mask: 61471,
            code: 61467,
            args: OpCodeArgs {
                n: 3840,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 292,
            display: "fmov.d @(R0,Rm),DRn".to_string(),
            mask: 61711,
            code: 61446,
            args: OpCodeArgs {
                n: 3584,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 293,
            display: "fmov.d @(R0,Rm),XDn".to_string(),
            mask: 61711,
            code: 61702,
            args: OpCodeArgs {
                n: 3584,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 294,
            display: "fmov.d DRm,@(R0,Rn)".to_string(),
            mask: 61471,
            code: 61447,
            args: OpCodeArgs {
                n: 3840,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 295,
            display: "fmov.d XDm,@(R0,Rn)".to_string(),
            mask: 61471,
            code: 61463,
            args: OpCodeArgs {
                n: 3840,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 298,
            display: "fldi0 FRn".to_string(),
            mask: 61695,
            code: 61581,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 299,
            display: "fldi1 FRn".to_string(),
            mask: 61695,
            code: 61597,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 300,
            display: "flds FRm,FPUL".to_string(),
            mask: 61695,
            code: 61469,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 301,
            display: "fsts FPUL,FRn".to_string(),
            mask: 61695,
            code: 61453,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 302,
            display: "fabs FRn".to_string(),
            mask: 61695,
            code: 61533,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 303,
            display: "fneg FRn".to_string(),
            mask: 61695,
            code: 61517,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 304,
            display: "fadd FRm,FRn".to_string(),
            mask: 61455,
            code: 61440,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 305,
            display: "fsub FRm,FRn".to_string(),
            mask: 61455,
            code: 61441,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 306,
            display: "fmul FRm,FRn".to_string(),
            mask: 61455,
            code: 61442,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 307,
            display: "fmac FR0,FRm,FRn".to_string(),
            mask: 61455,
            code: 61454,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 308,
            display: "fdiv FRm,FRn".to_string(),
            mask: 61455,
            code: 61443,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 309,
            display: "fsqrt FRn".to_string(),
            mask: 61695,
            code: 61549,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 310,
            display: "fcmp/eq FRm,FRn".to_string(),
            mask: 61455,
            code: 61444,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 311,
            display: "fcmp/gt FRm,FRn".to_string(),
            mask: 61455,
            code: 61445,
            args: OpCodeArgs {
                n: 3840,
                m: 240,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 312,
            display: "float FPUL,FRn".to_string(),
            mask: 61695,
            code: 61485,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 313,
            display: "ftrc FRm,FPUL".to_string(),
            mask: 61695,
            code: 61501,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 314,
            display: "fipr FVm,FVn".to_string(),
            mask: 61695,
            code: 61677,
            args: OpCodeArgs {
                n: 3072,
                m: 768,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 315,
            display: "ftrv XMTRX,FVn".to_string(),
            mask: 62463,
            code: 61949,
            args: OpCodeArgs {
                n: 3072,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 316,
            display: "fsrra FRn".to_string(),
            mask: 61695,
            code: 61565,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 317,
            display: "fsca FPUL,DRn".to_string(),
            mask: 61951,
            code: 61693,
            args: OpCodeArgs {
                n: 3584,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 318,
            display: "fabs DRn".to_string(),
            mask: 61951,
            code: 61533,
            args: OpCodeArgs {
                n: 3584,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 319,
            display: "fneg DRn".to_string(),
            mask: 61951,
            code: 61517,
            args: OpCodeArgs {
                n: 3584,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 320,
            display: "fadd DRm,DRn".to_string(),
            mask: 61727,
            code: 61440,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 321,
            display: "fsub DRm,DRn".to_string(),
            mask: 61727,
            code: 61441,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 322,
            display: "fmul DRm,DRn".to_string(),
            mask: 61727,
            code: 61442,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 323,
            display: "fdiv DRm,DRn".to_string(),
            mask: 61727,
            code: 61443,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 324,
            display: "fsqrt DRn".to_string(),
            mask: 61951,
            code: 61549,
            args: OpCodeArgs {
                n: 3584,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 325,
            display: "fcmp/eq DRm,DRn".to_string(),
            mask: 61727,
            code: 61444,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 326,
            display: "fcmp/gt DRm,DRn".to_string(),
            mask: 61727,
            code: 61445,
            args: OpCodeArgs {
                n: 3584,
                m: 224,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 327,
            display: "float FPUL,DRn".to_string(),
            mask: 61951,
            code: 61485,
            args: OpCodeArgs {
                n: 3584,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 328,
            display: "ftrc DRm,FPUL".to_string(),
            mask: 61951,
            code: 61501,
            args: OpCodeArgs {
                n: 0,
                m: 3584,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 329,
            display: "fcnvds DRm,FPUL".to_string(),
            mask: 61951,
            code: 61629,
            args: OpCodeArgs {
                n: 0,
                m: 3584,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 330,
            display: "fcnvsd FPUL,DRn".to_string(),
            mask: 61951,
            code: 61613,
            args: OpCodeArgs {
                n: 3584,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 331,
            display: "lds Rm,FPSCR".to_string(),
            mask: 61695,
            code: 16490,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 332,
            display: "sts FPSCR,Rn".to_string(),
            mask: 61695,
            code: 106,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 333,
            display: "lds.l @Rm+,FPSCR".to_string(),
            mask: 61695,
            code: 16486,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 334,
            display: "sts.l FPSCR,@-Rn".to_string(),
            mask: 61695,
            code: 16482,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 335,
            display: "lds Rm,FPUL".to_string(),
            mask: 61695,
            code: 16474,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 336,
            display: "sts FPUL,Rn".to_string(),
            mask: 61695,
            code: 90,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 337,
            display: "lds.l @Rm+,FPUL".to_string(),
            mask: 61695,
            code: 16470,
            args: OpCodeArgs {
                n: 0,
                m: 3840,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 338,
            display: "sts.l FPUL,@-Rn".to_string(),
            mask: 61695,
            code: 16466,
            args: OpCodeArgs {
                n: 3840,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 339,
            display: "frchg".to_string(),
            mask: 65535,
            code: 64509,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 340,
            display: "fschg".to_string(),
            mask: 65535,
            code: 62461,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,

        OpCode {
            id: 341,
            display: "fpchg".to_string(),
            mask: 65535,
            code: 63485,
            args: OpCodeArgs {
                n: 0,
                m: 0,
                d: 0,
                i: 0
            }
        } ,
    ];
}