// THIS CODE WAS GENERATED BY SH4GENERATOR v0.1.0 BY FRANCISZEK ŁOPUSZAŃSKI
// DO NOT EDIT THIS FILE!
use std::collections::HashMap;

#[allow(dead_code)]
struct OPCode {
    id: u32,
    name: &'static str,

    mask: u32,
    code: u32,
    args: HashMap<&'static str, u32>,
}

lazy_static! {
    static ref OPCODES_TABLE: [OPCode; 246] = [
        OPCode {
            id: 0,
            name: "mov R{m:d},R{n:d}",
            mask: 61455,
            code: 24579,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 1,
            name: "mov #h'{i:04x},R{n:d}",
            mask: 61440,
            code: 57344,
            args: HashMap::from([("i", 255), ("n", 3840)])
        } ,

        OPCode {
            id: 4,
            name: "mova @(R{d:d},PC),R0",
            mask: 65280,
            code: 50944,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 5,
            name: "mov.w @(R{d:d},PC),R{n:d}",
            mask: 61440,
            code: 36864,
            args: HashMap::from([("n", 3840), ("d", 255)])
        } ,

        OPCode {
            id: 6,
            name: "mov.l @(R{d:d},PC),R{n:d}",
            mask: 61440,
            code: 53248,
            args: HashMap::from([("n", 3840), ("d", 255)])
        } ,

        OPCode {
            id: 7,
            name: "mov.b @R{m:d},R{n:d}",
            mask: 61455,
            code: 24576,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 8,
            name: "mov.w @R{m:d},R{n:d}",
            mask: 61455,
            code: 24577,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 9,
            name: "mov.l @R{m:d},R{n:d}",
            mask: 61455,
            code: 24578,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 10,
            name: "mov.b R{m:d},@R{n:d}",
            mask: 61455,
            code: 8192,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 11,
            name: "mov.w R{m:d},@R{n:d}",
            mask: 61455,
            code: 8193,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 12,
            name: "mov.l R{m:d},@R{n:d}",
            mask: 61455,
            code: 8194,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 13,
            name: "mov.b @R{m:d}+,R{n:d}",
            mask: 61455,
            code: 24580,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 14,
            name: "mov.w @R{m:d}+,R{n:d}",
            mask: 61455,
            code: 24581,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 15,
            name: "mov.l @R{m:d}+,R{n:d}",
            mask: 61455,
            code: 24582,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 16,
            name: "mov.b R{m:d},@-R{n:d}",
            mask: 61455,
            code: 8196,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 17,
            name: "mov.w R{m:d},@-R{n:d}",
            mask: 61455,
            code: 8197,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 18,
            name: "mov.l R{m:d},@-R{n:d}",
            mask: 61455,
            code: 8198,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 25,
            name: "mov.b @(R{d:d},R{m:d}),R0",
            mask: 65280,
            code: 33792,
            args: HashMap::from([("m", 240), ("d", 15)])
        } ,

        OPCode {
            id: 28,
            name: "mov.w @(R{d:d},R{m:d}),R0",
            mask: 65280,
            code: 34048,
            args: HashMap::from([("d", 15), ("m", 240)])
        } ,

        OPCode {
            id: 31,
            name: "mov.l @(R{d:d},R{m:d}),R{n:d}",
            mask: 61440,
            code: 20480,
            args: HashMap::from([("n", 3840), ("m", 240), ("d", 15)])
        } ,

        OPCode {
            id: 33,
            name: "mov.b R0,@(R{d:d},R{n:d})",
            mask: 65280,
            code: 32768,
            args: HashMap::from([("n", 240), ("d", 15)])
        } ,

        OPCode {
            id: 35,
            name: "mov.w R0,@(R{d:d},R{n:d})",
            mask: 65280,
            code: 33024,
            args: HashMap::from([("n", 240), ("d", 15)])
        } ,

        OPCode {
            id: 37,
            name: "mov.l R{m:d},@(R{d:d},R{n:d})",
            mask: 61440,
            code: 4096,
            args: HashMap::from([("m", 240), ("n", 3840), ("d", 15)])
        } ,

        OPCode {
            id: 39,
            name: "mov.b @(R0,R{m:d}),R{n:d}",
            mask: 61455,
            code: 12,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 40,
            name: "mov.w @(R0,R{m:d}),R{n:d}",
            mask: 61455,
            code: 13,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 41,
            name: "mov.l @(R0,R{m:d}),R{n:d}",
            mask: 61455,
            code: 14,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 42,
            name: "mov.b R{m:d},@(R0,R{n:d})",
            mask: 61455,
            code: 4,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 43,
            name: "mov.w R{m:d},@(R0,R{n:d})",
            mask: 61455,
            code: 5,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 44,
            name: "mov.l R{m:d},@(R0,R{n:d})",
            mask: 61455,
            code: 6,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 45,
            name: "mov.b @(R{d:d},GBR),R0",
            mask: 65280,
            code: 50176,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 46,
            name: "mov.w @(R{d:d},GBR),R0",
            mask: 65280,
            code: 50432,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 47,
            name: "mov.l @(R{d:d},GBR),R0",
            mask: 65280,
            code: 50688,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 48,
            name: "mov.b R0,@(R{d:d},GBR)",
            mask: 65280,
            code: 49152,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 49,
            name: "mov.w R0,@(R{d:d},GBR)",
            mask: 65280,
            code: 49408,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 50,
            name: "mov.l R0,@(R{d:d},GBR)",
            mask: 65280,
            code: 49664,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 51,
            name: "movco.l R0,@R{n:d}",
            mask: 61695,
            code: 115,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 52,
            name: "movli.l @R{m:d},R0",
            mask: 61695,
            code: 99,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 53,
            name: "movua.l @R{m:d},R0",
            mask: 61695,
            code: 16553,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 54,
            name: "movua.l @R{m:d}+,R0",
            mask: 61695,
            code: 16617,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 60,
            name: "movt R{n:d}",
            mask: 61695,
            code: 41,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 62,
            name: "swap.b R{m:d},R{n:d}",
            mask: 61455,
            code: 24584,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 63,
            name: "swap.w R{m:d},R{n:d}",
            mask: 61455,
            code: 24585,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 64,
            name: "xtrct R{m:d},R{n:d}",
            mask: 61455,
            code: 8205,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 79,
            name: "add R{m:d},R{n:d}",
            mask: 61455,
            code: 12300,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 80,
            name: "add #h'{i:04x},R{n:d}",
            mask: 61440,
            code: 28672,
            args: HashMap::from([("n", 3840), ("i", 255)])
        } ,

        OPCode {
            id: 81,
            name: "addc R{m:d},R{n:d}",
            mask: 61455,
            code: 12302,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 82,
            name: "addv R{m:d},R{n:d}",
            mask: 61455,
            code: 12303,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 83,
            name: "cmp/eq #h'{i:04x},R0",
            mask: 65280,
            code: 34816,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 84,
            name: "cmp/eq R{m:d},R{n:d}",
            mask: 61455,
            code: 12288,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 85,
            name: "cmp/hs R{m:d},R{n:d}",
            mask: 61455,
            code: 12290,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 86,
            name: "cmp/ge R{m:d},R{n:d}",
            mask: 61455,
            code: 12291,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 87,
            name: "cmp/hi R{m:d},R{n:d}",
            mask: 61455,
            code: 12294,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 88,
            name: "cmp/gt R{m:d},R{n:d}",
            mask: 61455,
            code: 12295,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 89,
            name: "cmp/pl R{n:d}",
            mask: 61695,
            code: 16405,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 90,
            name: "cmp/pz R{n:d}",
            mask: 61695,
            code: 16401,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 91,
            name: "cmp/str R{m:d},R{n:d}",
            mask: 61455,
            code: 8204,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 96,
            name: "div0s R{m:d},R{n:d}",
            mask: 61455,
            code: 8199,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 97,
            name: "div0u",
            mask: 65535,
            code: 25,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 98,
            name: "div1 R{m:d},R{n:d}",
            mask: 61455,
            code: 12292,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 101,
            name: "dmuls.l R{m:d},R{n:d}",
            mask: 61455,
            code: 12301,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 102,
            name: "dmulu.l R{m:d},R{n:d}",
            mask: 61455,
            code: 12293,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 103,
            name: "dt R{n:d}",
            mask: 61695,
            code: 16400,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 104,
            name: "exts.b R{m:d},R{n:d}",
            mask: 61455,
            code: 24590,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 105,
            name: "exts.w R{m:d},R{n:d}",
            mask: 61455,
            code: 24591,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 106,
            name: "extu.b R{m:d},R{n:d}",
            mask: 61455,
            code: 24588,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 107,
            name: "extu.w R{m:d},R{n:d}",
            mask: 61455,
            code: 24589,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 108,
            name: "mac.l @R{m:d}+,@R{n:d}+",
            mask: 61455,
            code: 15,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 109,
            name: "mac.w @R{m:d}+,@R{n:d}+",
            mask: 61455,
            code: 16399,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 110,
            name: "mul.l R{m:d},R{n:d}",
            mask: 61455,
            code: 7,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 112,
            name: "muls.w R{m:d},R{n:d}",
            mask: 61455,
            code: 8207,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 113,
            name: "mulu.w R{m:d},R{n:d}",
            mask: 61455,
            code: 8206,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 114,
            name: "neg R{m:d},R{n:d}",
            mask: 61455,
            code: 24587,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 115,
            name: "negc R{m:d},R{n:d}",
            mask: 61455,
            code: 24586,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 116,
            name: "sub R{m:d},R{n:d}",
            mask: 61455,
            code: 12296,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 117,
            name: "subc R{m:d},R{n:d}",
            mask: 61455,
            code: 12298,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 118,
            name: "subv R{m:d},R{n:d}",
            mask: 61455,
            code: 12299,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 119,
            name: "and R{m:d},R{n:d}",
            mask: 61455,
            code: 8201,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 120,
            name: "and #h'{i:04x},R0",
            mask: 65280,
            code: 51456,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 121,
            name: "and.b #h'{i:04x},@(R0,GBR)",
            mask: 65280,
            code: 52480,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 122,
            name: "not R{m:d},R{n:d}",
            mask: 61455,
            code: 24583,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 123,
            name: "or R{m:d},R{n:d}",
            mask: 61455,
            code: 8203,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 124,
            name: "or #h'{i:04x},R0",
            mask: 65280,
            code: 51968,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 125,
            name: "or.b #h'{i:04x},@(R0,GBR)",
            mask: 65280,
            code: 52992,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 126,
            name: "tas.b @R{n:d}",
            mask: 61695,
            code: 16411,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 127,
            name: "tst R{m:d},R{n:d}",
            mask: 61455,
            code: 8200,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 128,
            name: "tst #h'{i:04x},R0",
            mask: 65280,
            code: 51200,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 129,
            name: "tst.b #h'{i:04x},@(R0,GBR)",
            mask: 65280,
            code: 52224,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 130,
            name: "xor R{m:d},R{n:d}",
            mask: 61455,
            code: 8202,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 131,
            name: "xor #h'{i:04x},R0",
            mask: 65280,
            code: 51712,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 132,
            name: "xor.b #h'{i:04x},@(R0,GBR)",
            mask: 65280,
            code: 52736,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 133,
            name: "rotcl R{n:d}",
            mask: 61695,
            code: 16420,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 134,
            name: "rotcr R{n:d}",
            mask: 61695,
            code: 16421,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 135,
            name: "rotl R{n:d}",
            mask: 61695,
            code: 16388,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 136,
            name: "rotr R{n:d}",
            mask: 61695,
            code: 16389,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 137,
            name: "shad R{m:d},R{n:d}",
            mask: 61455,
            code: 16396,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 138,
            name: "shal R{n:d}",
            mask: 61695,
            code: 16416,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 139,
            name: "shar R{n:d}",
            mask: 61695,
            code: 16417,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 140,
            name: "shld R{m:d},R{n:d}",
            mask: 61455,
            code: 16397,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 141,
            name: "shll R{n:d}",
            mask: 61695,
            code: 16384,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 142,
            name: "shll2 R{n:d}",
            mask: 61695,
            code: 16392,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 143,
            name: "shll8 R{n:d}",
            mask: 61695,
            code: 16408,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 144,
            name: "shll16 R{n:d}",
            mask: 61695,
            code: 16424,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 145,
            name: "shlr R{n:d}",
            mask: 61695,
            code: 16385,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 146,
            name: "shlr2 R{n:d}",
            mask: 61695,
            code: 16393,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 147,
            name: "shlr8 R{n:d}",
            mask: 61695,
            code: 16409,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 148,
            name: "shlr16 R{n:d}",
            mask: 61695,
            code: 16425,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 149,
            name: "bf label",
            mask: 65280,
            code: 35584,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 150,
            name: "bf/s label",
            mask: 65280,
            code: 36608,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 151,
            name: "bt label",
            mask: 65280,
            code: 35072,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 152,
            name: "bt/s label",
            mask: 65280,
            code: 36096,
            args: HashMap::from([("d", 255)])
        } ,

        OPCode {
            id: 153,
            name: "bra label",
            mask: 61440,
            code: 40960,
            args: HashMap::from([("d", 4095)])
        } ,

        OPCode {
            id: 154,
            name: "braf R{m:d}",
            mask: 61695,
            code: 35,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 155,
            name: "bsr label",
            mask: 61440,
            code: 45056,
            args: HashMap::from([("d", 4095)])
        } ,

        OPCode {
            id: 156,
            name: "bsrf R{m:d}",
            mask: 61695,
            code: 3,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 157,
            name: "jmp @R{m:d}",
            mask: 61695,
            code: 16427,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 158,
            name: "jsr @R{m:d}",
            mask: 61695,
            code: 16395,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 161,
            name: "rts",
            mask: 65535,
            code: 11,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 164,
            name: "clrmac",
            mask: 65535,
            code: 40,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 165,
            name: "clrs",
            mask: 65535,
            code: 72,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 166,
            name: "clrt",
            mask: 65535,
            code: 8,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 167,
            name: "icbi @R{n:d}",
            mask: 61695,
            code: 227,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 169,
            name: "ldc R{m:d},SR",
            mask: 61695,
            code: 16398,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 170,
            name: "ldc.l @R{m:d}+,SR",
            mask: 61695,
            code: 16391,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 172,
            name: "ldc R{m:d},GBR",
            mask: 61695,
            code: 16414,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 173,
            name: "ldc.l @R{m:d}+,GBR",
            mask: 61695,
            code: 16407,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 174,
            name: "ldc R{m:d},VBR",
            mask: 61695,
            code: 16430,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 175,
            name: "ldc.l @R{m:d}+,VBR",
            mask: 61695,
            code: 16423,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 182,
            name: "ldc R{m:d},SGR",
            mask: 61695,
            code: 16442,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 183,
            name: "ldc.l @R{m:d}+,SGR",
            mask: 61695,
            code: 16438,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 184,
            name: "ldc R{m:d},SSR",
            mask: 61695,
            code: 16446,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 185,
            name: "ldc.l @R{m:d}+,SSR",
            mask: 61695,
            code: 16439,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 186,
            name: "ldc R{m:d},SPC",
            mask: 61695,
            code: 16462,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 187,
            name: "ldc.l @R{m:d}+,SPC",
            mask: 61695,
            code: 16455,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 188,
            name: "ldc R{m:d},DBR",
            mask: 61695,
            code: 16634,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 189,
            name: "ldc.l @R{m:d}+,DBR",
            mask: 61695,
            code: 16630,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 190,
            name: "ldc R{m:d},R{n:d}_BANK",
            mask: 61583,
            code: 16526,
            args: HashMap::from([("n", 112), ("m", 3840)])
        } ,

        OPCode {
            id: 191,
            name: "ldc.l @R{m:d}+,R{n:d}_BANK",
            mask: 61583,
            code: 16519,
            args: HashMap::from([("n", 112), ("m", 3840)])
        } ,

        OPCode {
            id: 194,
            name: "lds R{m:d},MACH",
            mask: 61695,
            code: 16394,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 195,
            name: "lds.l @R{m:d}+,MACH",
            mask: 61695,
            code: 16390,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 196,
            name: "lds R{m:d},MACL",
            mask: 61695,
            code: 16410,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 197,
            name: "lds.l @R{m:d}+,MACL",
            mask: 61695,
            code: 16406,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 198,
            name: "lds R{m:d},PR",
            mask: 61695,
            code: 16426,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 199,
            name: "lds.l @R{m:d}+,PR",
            mask: 61695,
            code: 16422,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 212,
            name: "ldtlb",
            mask: 65535,
            code: 56,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 213,
            name: "movca.l R0,@R{n:d}",
            mask: 61695,
            code: 195,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 214,
            name: "nop",
            mask: 65535,
            code: 9,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 215,
            name: "ocbi @R{n:d}",
            mask: 61695,
            code: 147,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 216,
            name: "ocbp @R{n:d}",
            mask: 61695,
            code: 163,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 217,
            name: "ocbwb @R{n:d}",
            mask: 61695,
            code: 179,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 218,
            name: "pref @R{n:d}",
            mask: 61695,
            code: 131,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 219,
            name: "prefi @R{n:d}",
            mask: 61695,
            code: 211,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 221,
            name: "rte",
            mask: 65535,
            code: 43,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 224,
            name: "sets",
            mask: 65535,
            code: 88,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 225,
            name: "sett",
            mask: 65535,
            code: 24,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 226,
            name: "sleep",
            mask: 65535,
            code: 27,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 228,
            name: "stc SR,R{n:d}",
            mask: 61695,
            code: 2,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 229,
            name: "stc.l SR,@-R{n:d}",
            mask: 61695,
            code: 16387,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 231,
            name: "stc GBR,R{n:d}",
            mask: 61695,
            code: 18,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 232,
            name: "stc.l GBR,@-R{n:d}",
            mask: 61695,
            code: 16403,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 233,
            name: "stc VBR,R{n:d}",
            mask: 61695,
            code: 34,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 234,
            name: "stc.l VBR,@-R{n:d}",
            mask: 61695,
            code: 16419,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 241,
            name: "stc SGR,R{n:d}",
            mask: 61695,
            code: 58,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 242,
            name: "stc.l SGR,@-R{n:d}",
            mask: 61695,
            code: 16434,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 243,
            name: "stc SSR,R{n:d}",
            mask: 61695,
            code: 50,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 244,
            name: "stc.l SSR,@-R{n:d}",
            mask: 61695,
            code: 16435,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 245,
            name: "stc SPC,R{n:d}",
            mask: 61695,
            code: 66,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 246,
            name: "stc.l SPC,@-R{n:d}",
            mask: 61695,
            code: 16451,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 247,
            name: "stc DBR,R{n:d}",
            mask: 61695,
            code: 250,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 248,
            name: "stc.l DBR,@-R{n:d}",
            mask: 61695,
            code: 16626,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 249,
            name: "stc R{m:d}_BANK,R{n:d}",
            mask: 61583,
            code: 130,
            args: HashMap::from([("n", 3840), ("m", 112)])
        } ,

        OPCode {
            id: 250,
            name: "stc.l R{m:d}_BANK,@-R{n:d}",
            mask: 61583,
            code: 16515,
            args: HashMap::from([("n", 3840), ("m", 112)])
        } ,

        OPCode {
            id: 251,
            name: "sts MACH,R{n:d}",
            mask: 61695,
            code: 10,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 252,
            name: "sts.l MACH,@-R{n:d}",
            mask: 61695,
            code: 16386,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 253,
            name: "sts MACL,R{n:d}",
            mask: 61695,
            code: 26,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 254,
            name: "sts.l MACL,@-R{n:d}",
            mask: 61695,
            code: 16402,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 255,
            name: "sts PR,R{n:d}",
            mask: 61695,
            code: 42,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 256,
            name: "sts.l PR,@-R{n:d}",
            mask: 61695,
            code: 16418,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 269,
            name: "synco",
            mask: 65535,
            code: 171,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 270,
            name: "trapa #h'{i:04x}",
            mask: 65280,
            code: 49920,
            args: HashMap::from([("i", 255)])
        } ,

        OPCode {
            id: 271,
            name: "fmov FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61452,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 272,
            name: "fmov.s @R{m:d},FR{n:d}",
            mask: 61455,
            code: 61448,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 273,
            name: "fmov.s FR{m:d},@R{n:d}",
            mask: 61455,
            code: 61450,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 274,
            name: "fmov.s @R{m:d}+,FR{n:d}",
            mask: 61455,
            code: 61449,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 275,
            name: "fmov.s FR{m:d},@-R{n:d}",
            mask: 61455,
            code: 61451,
            args: HashMap::from([("m", 240), ("n", 3840)])
        } ,

        OPCode {
            id: 276,
            name: "fmov.s @(R0,R{m:d}),FR{n:d}",
            mask: 61455,
            code: 61446,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 277,
            name: "fmov.s FR{m:d},@(R0,R{n:d})",
            mask: 61455,
            code: 61447,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 280,
            name: "fmov DR{m:d},DR{n:d}",
            mask: 61727,
            code: 61452,
            args: HashMap::from([("m", 224), ("n", 3584)])
        } ,

        OPCode {
            id: 281,
            name: "fmov DR{m:d},XDn",
            mask: 61727,
            code: 61708,
            args: HashMap::from([("n", 3584), ("m", 224)])
        } ,

        OPCode {
            id: 282,
            name: "fmov XDm,DR{n:d}",
            mask: 61727,
            code: 61468,
            args: HashMap::from([("m", 224), ("n", 3584)])
        } ,

        OPCode {
            id: 283,
            name: "fmov XDm,XDn",
            mask: 61727,
            code: 61724,
            args: HashMap::from([("m", 224), ("n", 3584)])
        } ,

        OPCode {
            id: 284,
            name: "fmov.d @R{m:d},DR{n:d}",
            mask: 61711,
            code: 61448,
            args: HashMap::from([("n", 3584), ("m", 240)])
        } ,

        OPCode {
            id: 285,
            name: "fmov.d @R{m:d},XDn",
            mask: 61711,
            code: 61704,
            args: HashMap::from([("m", 240), ("n", 3584)])
        } ,

        OPCode {
            id: 286,
            name: "fmov.d DR{m:d},@R{n:d}",
            mask: 61471,
            code: 61450,
            args: HashMap::from([("n", 3840), ("m", 224)])
        } ,

        OPCode {
            id: 287,
            name: "fmov.d XDm,@R{n:d}",
            mask: 61471,
            code: 61466,
            args: HashMap::from([("m", 224), ("n", 3840)])
        } ,

        OPCode {
            id: 288,
            name: "fmov.d @R{m:d}+,DR{n:d}",
            mask: 61711,
            code: 61449,
            args: HashMap::from([("m", 240), ("n", 3584)])
        } ,

        OPCode {
            id: 289,
            name: "fmov.d @R{m:d}+,XDn",
            mask: 61711,
            code: 61705,
            args: HashMap::from([("n", 3584), ("m", 240)])
        } ,

        OPCode {
            id: 290,
            name: "fmov.d DR{m:d},@-R{n:d}",
            mask: 61471,
            code: 61451,
            args: HashMap::from([("n", 3840), ("m", 224)])
        } ,

        OPCode {
            id: 291,
            name: "fmov.d XDm,@-R{n:d}",
            mask: 61471,
            code: 61467,
            args: HashMap::from([("n", 3840), ("m", 224)])
        } ,

        OPCode {
            id: 292,
            name: "fmov.d @(R0,R{m:d}),DR{n:d}",
            mask: 61711,
            code: 61446,
            args: HashMap::from([("n", 3584), ("m", 240)])
        } ,

        OPCode {
            id: 293,
            name: "fmov.d @(R0,R{m:d}),XDn",
            mask: 61711,
            code: 61702,
            args: HashMap::from([("m", 240), ("n", 3584)])
        } ,

        OPCode {
            id: 294,
            name: "fmov.d DR{m:d},@(R0,R{n:d})",
            mask: 61471,
            code: 61447,
            args: HashMap::from([("n", 3840), ("m", 224)])
        } ,

        OPCode {
            id: 295,
            name: "fmov.d XDm,@(R0,R{n:d})",
            mask: 61471,
            code: 61463,
            args: HashMap::from([("m", 224), ("n", 3840)])
        } ,

        OPCode {
            id: 298,
            name: "fldi0 FR{n:d}",
            mask: 61695,
            code: 61581,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 299,
            name: "fldi1 FR{n:d}",
            mask: 61695,
            code: 61597,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 300,
            name: "flds FR{m:d},FPUL",
            mask: 61695,
            code: 61469,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 301,
            name: "fsts FPUL,FR{n:d}",
            mask: 61695,
            code: 61453,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 302,
            name: "fabs FR{n:d}",
            mask: 61695,
            code: 61533,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 303,
            name: "fneg FR{n:d}",
            mask: 61695,
            code: 61517,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 304,
            name: "fadd FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61440,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 305,
            name: "fsub FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61441,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 306,
            name: "fmul FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61442,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 307,
            name: "fmac FR0,FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61454,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 308,
            name: "fdiv FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61443,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 309,
            name: "fsqrt FR{n:d}",
            mask: 61695,
            code: 61549,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 310,
            name: "fcmp/eq FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61444,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 311,
            name: "fcmp/gt FR{m:d},FR{n:d}",
            mask: 61455,
            code: 61445,
            args: HashMap::from([("n", 3840), ("m", 240)])
        } ,

        OPCode {
            id: 312,
            name: "float FPUL,FR{n:d}",
            mask: 61695,
            code: 61485,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 313,
            name: "ftrc FR{m:d},FPUL",
            mask: 61695,
            code: 61501,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 314,
            name: "fipr FVm,FVn",
            mask: 61695,
            code: 61677,
            args: HashMap::from([("n", 3072), ("m", 768)])
        } ,

        OPCode {
            id: 315,
            name: "ftrv XMTRX,FVn",
            mask: 62463,
            code: 61949,
            args: HashMap::from([("n", 3072)])
        } ,

        OPCode {
            id: 316,
            name: "fsrra FR{n:d}",
            mask: 61695,
            code: 61565,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 317,
            name: "fsca FPUL,DR{n:d}",
            mask: 61951,
            code: 61693,
            args: HashMap::from([("n", 3584)])
        } ,

        OPCode {
            id: 318,
            name: "fabs DR{n:d}",
            mask: 61951,
            code: 61533,
            args: HashMap::from([("n", 3584)])
        } ,

        OPCode {
            id: 319,
            name: "fneg DR{n:d}",
            mask: 61951,
            code: 61517,
            args: HashMap::from([("n", 3584)])
        } ,

        OPCode {
            id: 320,
            name: "fadd DR{m:d},DR{n:d}",
            mask: 61727,
            code: 61440,
            args: HashMap::from([("n", 3584), ("m", 224)])
        } ,

        OPCode {
            id: 321,
            name: "fsub DR{m:d},DR{n:d}",
            mask: 61727,
            code: 61441,
            args: HashMap::from([("n", 3584), ("m", 224)])
        } ,

        OPCode {
            id: 322,
            name: "fmul DR{m:d},DR{n:d}",
            mask: 61727,
            code: 61442,
            args: HashMap::from([("n", 3584), ("m", 224)])
        } ,

        OPCode {
            id: 323,
            name: "fdiv DR{m:d},DR{n:d}",
            mask: 61727,
            code: 61443,
            args: HashMap::from([("m", 224), ("n", 3584)])
        } ,

        OPCode {
            id: 324,
            name: "fsqrt DR{n:d}",
            mask: 61951,
            code: 61549,
            args: HashMap::from([("n", 3584)])
        } ,

        OPCode {
            id: 325,
            name: "fcmp/eq DR{m:d},DR{n:d}",
            mask: 61727,
            code: 61444,
            args: HashMap::from([("n", 3584), ("m", 224)])
        } ,

        OPCode {
            id: 326,
            name: "fcmp/gt DR{m:d},DR{n:d}",
            mask: 61727,
            code: 61445,
            args: HashMap::from([("m", 224), ("n", 3584)])
        } ,

        OPCode {
            id: 327,
            name: "float FPUL,DR{n:d}",
            mask: 61951,
            code: 61485,
            args: HashMap::from([("n", 3584)])
        } ,

        OPCode {
            id: 328,
            name: "ftrc DR{m:d},FPUL",
            mask: 61951,
            code: 61501,
            args: HashMap::from([("m", 3584)])
        } ,

        OPCode {
            id: 329,
            name: "fcnvds DR{m:d},FPUL",
            mask: 61951,
            code: 61629,
            args: HashMap::from([("m", 3584)])
        } ,

        OPCode {
            id: 330,
            name: "fcnvsd FPUL,DR{n:d}",
            mask: 61951,
            code: 61613,
            args: HashMap::from([("n", 3584)])
        } ,

        OPCode {
            id: 331,
            name: "lds R{m:d},FPSCR",
            mask: 61695,
            code: 16490,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 332,
            name: "sts FPSCR,R{n:d}",
            mask: 61695,
            code: 106,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 333,
            name: "lds.l @R{m:d}+,FPSCR",
            mask: 61695,
            code: 16486,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 334,
            name: "sts.l FPSCR,@-R{n:d}",
            mask: 61695,
            code: 16482,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 335,
            name: "lds R{m:d},FPUL",
            mask: 61695,
            code: 16474,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 336,
            name: "sts FPUL,R{n:d}",
            mask: 61695,
            code: 90,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 337,
            name: "lds.l @R{m:d}+,FPUL",
            mask: 61695,
            code: 16470,
            args: HashMap::from([("m", 3840)])
        } ,

        OPCode {
            id: 338,
            name: "sts.l FPUL,@-R{n:d}",
            mask: 61695,
            code: 16466,
            args: HashMap::from([("n", 3840)])
        } ,

        OPCode {
            id: 339,
            name: "frchg",
            mask: 65535,
            code: 64509,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 340,
            name: "fschg",
            mask: 65535,
            code: 62461,
            args: HashMap::from([])
        } ,

        OPCode {
            id: 341,
            name: "fpchg",
            mask: 65535,
            code: 63485,
            args: HashMap::from([])
        } ,
    ];
}