// THIS CODE WAS GENERATED BY SH4GENERATOR v0.1.0 BY FRANCISZEK ŁOPUSZAŃSKI
// DO NOT EDIT THIS FILE!
use super::memory::SH4Memory;
use super::registers::SH4Registers;

#[allow(non_snake_case)]
pub trait SH4ISA {
    fn access_registers(&mut self) -> &mut SH4Registers;
    fn access_memory(&mut self) -> &mut SH4Memory;

    // TODO: Implement instruction args
    // TODO: Auto detect data usage and modify &self to &mut self if needed
    // TODO: Auto detect memory or register access and import them as needed
    fn MOV(&self) {
        todo!()
    }

    fn MOVI(&self) {
        todo!()
    }

    fn MOVA(&self) {
        todo!()
    }

    fn MOVWI(&self) {
        todo!()
    }

    fn MOVLI(&self) {
        todo!()
    }

    fn MOVBL(&self) {
        todo!()
    }

    fn MOVWL(&self) {
        todo!()
    }

    fn MOVLL(&self) {
        todo!()
    }

    fn MOVBS(&self) {
        todo!()
    }

    fn MOVWS(&self) {
        todo!()
    }

    fn MOVLS(&self) {
        todo!()
    }

    fn MOVBP(&self) {
        todo!()
    }

    fn MOVWP(&self) {
        todo!()
    }

    fn MOVLP(&self) {
        todo!()
    }

    fn MOVBM(&self) {
        todo!()
    }

    fn MOVWM(&self) {
        todo!()
    }

    fn MOVLM(&self) {
        todo!()
    }

    fn MOVBL4(&self) {
        todo!()
    }

    fn MOVWL4(&self) {
        todo!()
    }

    fn MOVLL4(&self) {
        todo!()
    }

    fn MOVBS4(&self) {
        todo!()
    }

    fn MOVWS4(&self) {
        todo!()
    }

    fn MOVLS4(&self) {
        todo!()
    }

    fn MOVBL0(&self) {
        todo!()
    }

    fn MOVWL0(&self) {
        todo!()
    }

    fn MOVLL0(&self) {
        todo!()
    }

    fn MOVBS0(&self) {
        todo!()
    }

    fn MOVWS0(&self) {
        todo!()
    }

    fn MOVLS0(&self) {
        todo!()
    }

    fn MOVBLG(&self) {
        todo!()
    }

    fn MOVWLG(&self) {
        todo!()
    }

    fn MOVLLG(&self) {
        todo!()
    }

    fn MOVBSG(&self) {
        todo!()
    }

    fn MOVWSG(&self) {
        todo!()
    }

    fn MOVLSG(&self) {
        todo!()
    }

    fn MOVCO(&self) {
        todo!()
    }

    fn MOVLINK(&self) {
        todo!()
    }

    fn MOVUAL(&self) {
        todo!()
    }

    fn MOVUALP(&self) {
        todo!()
    }

    fn MOVT(&self) {
        todo!()
    }

    fn SWAPB(&self) {
        todo!()
    }

    fn SWAPW(&self) {
        todo!()
    }

    fn XTRCT(&self) {
        todo!()
    }

    fn ADD(&self) {
        todo!()
    }

    fn ADDI(&self) {
        todo!()
    }

    fn ADDC(&self) {
        todo!()
    }

    fn ADDV(&self) {
        todo!()
    }

    fn CMPIM(&self) {
        todo!()
    }

    fn CMPEQ(&self) {
        todo!()
    }

    fn CMPHI(&self) {
        todo!()
    }

    fn CMPGE(&self) {
        todo!()
    }

    fn CMPHI_DUP(&self) {
        todo!()
    }

    fn CMPGT(&self) {
        todo!()
    }

    fn CMPPL(&self) {
        todo!()
    }

    fn CMPPZ(&self) {
        todo!()
    }

    fn CMPSTR(&self) {
        todo!()
    }

    fn DIV0S(&self) {
        todo!()
    }

    fn DIV0U(&self) {
        todo!()
    }

    fn DIV1(&self) {
        todo!()
    }

    fn DMULS(&self) {
        todo!()
    }

    fn DMULU(&self) {
        todo!()
    }

    fn DT(&self) {
        todo!()
    }

    fn EXTSB(&self) {
        todo!()
    }

    fn EXTSW(&self) {
        todo!()
    }

    fn EXTUB(&self) {
        todo!()
    }

    fn EXTUW(&self) {
        todo!()
    }

    fn MACL(&self) {
        todo!()
    }

    fn MACW(&self) {
        todo!()
    }

    fn MULL(&self) {
        todo!()
    }

    fn MULS(&self) {
        todo!()
    }

    fn MULU(&self) {
        todo!()
    }

    fn NEG(&self) {
        todo!()
    }

    fn NEGC(&self) {
        todo!()
    }

    fn SUB(&self) {
        todo!()
    }

    fn SUBC(&self) {
        todo!()
    }

    fn SUBV(&self) {
        todo!()
    }

    fn AND(&self) {
        todo!()
    }

    fn ANDI(&self) {
        todo!()
    }

    fn ANDM(&self) {
        todo!()
    }

    fn NOT(&self) {
        todo!()
    }

    fn OR(&self) {
        todo!()
    }

    fn ORI(&self) {
        todo!()
    }

    fn ORM(&self) {
        todo!()
    }

    fn TAS(&self) {
        todo!()
    }

    fn TST(&self) {
        todo!()
    }

    fn TSTI(&self) {
        todo!()
    }

    fn TSTM(&self) {
        todo!()
    }

    fn XOR(&self) {
        todo!()
    }

    fn XORI(&self) {
        todo!()
    }

    fn XORM(&self) {
        todo!()
    }

    fn ROTCL(&self) {
        todo!()
    }

    fn ROTCR(&self) {
        todo!()
    }

    fn ROTL(&self) {
        todo!()
    }

    fn ROTR(&self) {
        todo!()
    }

    fn SHAD(&self) {
        todo!()
    }

    fn SHAL(&self) {
        todo!()
    }

    fn SHAR(&self) {
        todo!()
    }

    fn SHLD(&self) {
        todo!()
    }

    fn SHLL(&self) {
        todo!()
    }

    fn SHLL2(&self) {
        todo!()
    }

    fn SHLL8(&self) {
        todo!()
    }

    fn SHLL16(&self) {
        todo!()
    }

    fn SHLR(&self) {
        todo!()
    }

    fn SHLR2(&self) {
        todo!()
    }

    fn SHLR8(&self) {
        todo!()
    }

    fn SHLR16(&self) {
        todo!()
    }

    fn BF(&self) {
        todo!()
    }

    fn BFS(&self) {
        todo!()
    }

    fn BT(&self) {
        todo!()
    }

    fn BTS(&self) {
        todo!()
    }

    fn BRA(&self) {
        todo!()
    }

    fn BRAF(&self) {
        todo!()
    }

    fn BSR(&self) {
        todo!()
    }

    fn BSRF(&self) {
        todo!()
    }

    fn JMP(&self) {
        todo!()
    }

    fn JSR(&self) {
        todo!()
    }

    fn RTS(&self) {
        todo!()
    }

    fn CLRMAC(&self) {
        todo!()
    }

    fn CLRS(&self) {
        todo!()
    }

    fn CLRT(&self) {
        todo!()
    }

    fn ICBI(&self) {
        todo!()
    }

    fn LDCSR(&self) {
        todo!()
    }

    fn LDCMSR(&self) {
        todo!()
    }

    fn LDCGBR(&self) {
        todo!()
    }

    fn LDCMGBR(&self) {
        todo!()
    }

    fn LDCVBR(&self) {
        todo!()
    }

    fn LDCMVBR(&self) {
        todo!()
    }

    fn LDCSGR(&self) {
        todo!()
    }

    fn LDCMSGR(&self) {
        todo!()
    }

    fn LDCSSR(&self) {
        todo!()
    }

    fn LDCMSSR(&self) {
        todo!()
    }

    fn LDCSPC(&self) {
        todo!()
    }

    fn LDCMSPC(&self) {
        todo!()
    }

    fn LDCDBR(&self) {
        todo!()
    }

    fn LDCMDBR(&self) {
        todo!()
    }

    fn LDCRn_BANK(&self) {
        todo!()
    }

    fn LDCMRn_BANK(&self) {
        todo!()
    }

    fn LDSMACH(&self) {
        todo!()
    }

    fn LDSMMACH(&self) {
        todo!()
    }

    fn LDSMACL(&self) {
        todo!()
    }

    fn LDSMMACL(&self) {
        todo!()
    }

    fn LDSPR(&self) {
        todo!()
    }

    fn LDSMPR(&self) {
        todo!()
    }

    fn LDTLB(&self) {
        todo!()
    }

    fn MOVCAL(&self) {
        todo!()
    }

    fn NOP(&self) {
        todo!()
    }

    fn OCBI(&self) {
        todo!()
    }

    fn OCBP(&self) {
        todo!()
    }

    fn OCBWB(&self) {
        todo!()
    }

    fn PREF(&self) {
        todo!()
    }

    fn PREFI(&self) {
        todo!()
    }

    fn RTE(&self) {
        todo!()
    }

    fn SETS(&self) {
        todo!()
    }

    fn SETT(&self) {
        todo!()
    }

    fn SLEEP(&self) {
        todo!()
    }

    fn STCSR(&self) {
        todo!()
    }

    fn STCMSR(&self) {
        todo!()
    }

    fn STCGBR(&self) {
        todo!()
    }

    fn STCMGBR(&self) {
        todo!()
    }

    fn STCVBR(&self) {
        todo!()
    }

    fn STCMVBR(&self) {
        todo!()
    }

    fn STCSGR(&self) {
        todo!()
    }

    fn STCMSGR(&self) {
        todo!()
    }

    fn STCSSR(&self) {
        todo!()
    }

    fn STCMSSR(&self) {
        todo!()
    }

    fn STCSPC(&self) {
        todo!()
    }

    fn STCMSPC(&self) {
        todo!()
    }

    fn STCDBR(&self) {
        todo!()
    }

    fn STCMDBR(&self) {
        todo!()
    }

    fn STCRm_BANK(&self) {
        todo!()
    }

    fn STCMRm_BANK(&self) {
        todo!()
    }

    fn STSMACH(&self) {
        todo!()
    }

    fn STSMMACH(&self) {
        todo!()
    }

    fn STSMACL(&self) {
        todo!()
    }

    fn STSMMACL(&self) {
        todo!()
    }

    fn STSPR(&self) {
        todo!()
    }

    fn STSMPR(&self) {
        todo!()
    }

    fn SYNCO(&self) {
        todo!()
    }

    fn TRAPA(&self) {
        todo!()
    }

    fn FMOV(&self) {
        todo!()
    }

    fn FMOV_LOAD(&self) {
        todo!()
    }

    fn FMOV_STORE(&self) {
        todo!()
    }

    fn FMOV_RESTORE(&self) {
        todo!()
    }

    fn FMOV_SAVE(&self) {
        todo!()
    }

    fn FMOV_INDEX_LOAD(&self) {
        todo!()
    }

    fn FMOV_INDEX_STORE(&self) {
        todo!()
    }

    fn FMOV_DR(&self) {
        todo!()
    }

    fn FMOV_DRXD(&self) {
        todo!()
    }

    fn FMOV_XDDR(&self) {
        todo!()
    }

    fn FMOV_XDXD(&self) {
        todo!()
    }

    fn FMOV_LOAD_DR(&self) {
        todo!()
    }

    fn FMOV_LOAD_XD(&self) {
        todo!()
    }

    fn FMOV_STORE_DR(&self) {
        todo!()
    }

    fn FMOV_STORE_XD(&self) {
        todo!()
    }

    fn FMOV_RESTORE_DR(&self) {
        todo!()
    }

    fn FMOV_RESTORE_XD(&self) {
        todo!()
    }

    fn FMOV_SAVE_DR(&self) {
        todo!()
    }

    fn FMOV_SAVE_XD(&self) {
        todo!()
    }

    fn FMOV_INDEX_LOAD_DR(&self) {
        todo!()
    }

    fn FMOV_INDEX_LOAD_XD(&self) {
        todo!()
    }

    fn FMOV_INDEX_STORE_DR(&self) {
        todo!()
    }

    fn FMOV_INDEX_STORE_XD(&self) {
        todo!()
    }

    fn FLDI0(&self) {
        todo!()
    }

    fn FLDI1(&self) {
        todo!()
    }

    fn FLDS(&self) {
        todo!()
    }

    fn FSTS(&self) {
        todo!()
    }

    fn FABS(&self) {
        todo!()
    }

    fn FNEG(&self) {
        todo!()
    }

    fn FADD(&self) {
        todo!()
    }

    fn FSUB(&self) {
        todo!()
    }

    fn FMUL(&self) {
        todo!()
    }

    fn FMAC(&self) {
        todo!()
    }

    fn FDIV(&self) {
        todo!()
    }

    fn FSQRT(&self) {
        todo!()
    }

    fn FCMP_EQ(&self) {
        todo!()
    }

    fn FCMP_GT(&self) {
        todo!()
    }

    fn FLOAT_single(&self) {
        todo!()
    }

    fn FTRC_single(&self) {
        todo!()
    }

    fn FIPR(&self) {
        todo!()
    }

    fn FTRV(&self) {
        todo!()
    }

    fn FSRRA(&self) {
        todo!()
    }

    fn FSCA(&self) {
        todo!()
    }

    fn FABS_DUP(&self) {
        todo!()
    }

    fn FNEG_DUP(&self) {
        todo!()
    }

    fn FADD_DUP(&self) {
        todo!()
    }

    fn FSUB_DUP(&self) {
        todo!()
    }

    fn FMUL_DUP(&self) {
        todo!()
    }

    fn FDIV_DUP(&self) {
        todo!()
    }

    fn FSQRT_DUP(&self) {
        todo!()
    }

    fn FCMP_EQ_DUP(&self) {
        todo!()
    }

    fn FCMP_GT_DUP(&self) {
        todo!()
    }

    fn FLOAT_double(&self) {
        todo!()
    }

    fn FTRC_double(&self) {
        todo!()
    }

    fn FCNVDS(&self) {
        todo!()
    }

    fn FCNVSD(&self) {
        todo!()
    }

    fn LDSFPSCR(&self) {
        todo!()
    }

    fn STSFPSCR(&self) {
        todo!()
    }

    fn LDSMFPSCR(&self) {
        todo!()
    }

    fn STSMFPSCR(&self) {
        todo!()
    }

    fn LDSFPUL(&self) {
        todo!()
    }

    fn STSFPUL(&self) {
        todo!()
    }

    fn LDSMFPUL(&self) {
        todo!()
    }

    fn STSMFPUL(&self) {
        todo!()
    }

    fn FRCHG(&self) {
        todo!()
    }

    fn FSCHG(&self) {
        todo!()
    }

    fn FPCHG(&self) {
        todo!()
    }
}
