use genco::prelude::*;
use scraper::{Html, Selector};

use super::helper::get_nth_cell_of_table;

pub fn generate_impl_empty(html_content: &str) -> rust::Tokens {
    // Parse table from HTML
    let document = Html::parse_document(html_content);

    let row_selector = Selector::parse(r#"div.col_cont"#).unwrap();
    let mut function_names: Vec<String> = vec![];
    let mut function_abstracts: Vec<String> = vec![];
    let mut function_idx: Vec<u32> = vec![];

    for (i, row) in document.select(&row_selector).enumerate() {
        let arch = get_nth_cell_of_table(&row, 1);

        if !arch.contains("SH4") && !arch.contains("SH4A") {
            continue;
        }

        let col_cont_selector = Selector::parse(r#"div.col_cont_note"#).unwrap();
        let col_cont = row.select(&col_cont_selector).next().unwrap();

        let precode_selector = Selector::parse(r#"pre"#).unwrap();
        let precode = col_cont
            .select(&precode_selector)
            .next()
            .unwrap()
            .text()
            .collect::<String>();

        // TODO: Replace this trash with nom or pest parser
        for line in precode.lines() {
            if let Some(first) = line.split(' ').next() {
                if first == "#define" || line.trim().is_empty() {
                    continue;
                }

                let mut name: String = if first != "void" {
                    first.to_string()
                } else {
                    line.split(' ').nth(1).unwrap().to_string()
                };

                let function_abstract = get_nth_cell_of_table(&row, 3);
                function_abstracts.push(function_abstract);

                function_idx.push(i as u32);
                if function_names.contains(&name) {
                    name += "_DUP"
                }

                function_names.push(name);
                break;
            }
        }
    }

    quote! {
        $(format!("// THIS CODE WAS GENERATED BY SH4GENERATOR v{} BY FRANCISZEK ŁOPUSZAŃSKI", env!("CARGO_PKG_VERSION")))
        #![allow(unused)]
        use crate::{
            cpu::CPU,
            opcodes::{OpCode, OpCodeArgs},
        };

        #[allow(non_snake_case)]
        impl CPU {
            fn sign_extend(x: u16) -> u32 {
                if (x & 0x80) == 0 {
                    x as u32 & 0x000_000FF
                } else {
                    x as u32 | 0xFFFF_FF00
                }
            }

            pub fn execute(&mut self, opcode: OpCode) {
                match opcode.id {
                    $(for (name, i) in function_names.iter().zip(function_idx.iter()) => $(quote!(
                        $(*i) => self.$name(opcode.args),$("\n")
                    )))
                    _ => {
                        println!("OUT OF RANGE OPCODE: {:#?}", opcode);
                        todo!()
                    }
                }
            }

            $(for (name, abst) in function_names.iter().zip(function_abstracts.iter()) => $(quote!(
                pub fn $name(&mut self, args: OpCodeArgs){
                    $(format!("/* {} */", abst))
                    todo!()
                }$['\n']
            )))
        }
    }
}
